# Generated by Django 3.2.7 on 2022-02-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220211_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.TextField(blank=True),
        ),
    ]
